print('Exercício 1')
print('Hello World')
print('--------------')
print('Exercício 2')
numero_informado1 = input('Escreva um número: ')
print('--------------')
print('Exercício 3')
numero_informado2 = input('Escreva outro número: ')
print('A soma dos números informados é: ', sum([int(numero_informado1), int(numero_informado2)]))
print('--------------')
